import {
  IconAppWindow,
  IconBrandInstagram,
  IconMail,
  IconPhone,
} from "@tabler/icons-react"

export const curriculumVitae = [
  {
    start: "2021",
    finish: "2023",
    title: "Front End Web Developer",
    company: "Valk Digital",
    url: "https://www.valkdigital.nl/",
    description: "kadaver",
  },
  {
    start: "2020",
    finish: "heden",
    title: "Content Creator",
    company: "Kibbeling Media",
    url: "https://www.kibbelingmedia.nl/",
    description: "kadaver",
  },
  {
    start: "2020",
    finish: "2022",
    title: "Oprichten Muziekschool",
    company: "School Of Beats",
    url: "https://schoolofbeats.nl/",
    description: "kadaver",
  },
  {
    start: "2020",
    finish: "2022",
    title: "Educatieve Content creator",
    company: "Kunst Centraal",
    url: "https://kunstcentraal.nl/",
    description: "kadaver",
  },
  {
    start: "2019",
    finish: "2020",
    title: "Organisator Rarara-evenementen",
    description: "kadaver",
  },
  {
    start: "2017",
    finish: "2020",
    title: "Artistiek coördinator & docent bij de Boempatsers",
    company: "Cultuurhuis Kanaleneiland",
    url: "https://bokscultuurhuis.nl/",
    description: "kadaver",
  },
  {
    start: "2017",
    finish: "2018",
    title: "Muziekworkshops in gesloten inrichtingen",
    description: "kadaver",
  },
  {
    start: "2016",
    finish: "2018",
    title: "Projectmanager evenementen",
    company: "Bankra Bike",
    url: "https://bankrabike.nl/",
    description: "kadaver",
  },
  {
    start: "2016",
    finish: "heden",
    title: "Componist & Music-Producer voor Media",
    description: "kadaver",
  },
  {
    start: "2016",
    finish: "2018",
    title: "Docent Piano in Overvecht Utrecht",
    company: "UCK",
    description: "kadaver",
  },
  {
    start: "2014",
    finish: "2016",
    title: "Docent percussie",
    company: "Muziekroute",
    url: "https://www.muziekroute.nl/",
    description: "kadaver",
  },
  {
    start: "2013",
    finish: "2016",
    title: "Docent Dj & Synthese/Sound Design",
    company: "Emstudios Academy Of Sound",
    description: "kadaver",
  },
  {
    start: "2011",
    finish: "2014",
    title: "Artist in residence bij Habek/Kytopia",
    description: "kadaver",
  },
  {
    start: "2011",
    finish: "2021",
    title: "Docent Dj en turntablism",
    company: "Dutch Dj Academy",
    url: "https://www.dutchdjacademy.com/",
    description: "kadaver",
  },
  {
    start: "2011",
    finish: "2012",
    title: "Docent Dj en turntablism",
    company: "NPAC ROC",
    description: "kadaver",
  },
  {
    start: "2010",
    finish: "2022",
    title: "Cultureel ondernemer bij Prace Music",
    description: "kadaver",
  },
  {
    start: "2009",
    finish: "2021",
    title: "Docent piano aan huis",
    // description: "kadaver",
  },
  {
    start: "2009",
    finish: "2010",
    title: "Initiatiefnemer muziekproject 'The First Statement'",
    description: "kadaver",
  },
  {
    start: "2004",
    finish: "2021",
    title: "DJ, Pianist, Performer bij diverse evenementen",
    description: "kadaver",
  },
]

export const contactInfo = [
  {
    icon: <IconPhone />,
    text: "06 185 120 84",
  },
  {
    icon: <IconMail />,
    text: "joramkroon@live.nl",
  },
  {
    icon: <IconBrandInstagram />,
    text: "Instagram/pracemusic",
    url: "https://www.instagram.com/pracemusic",
  },
  {
    icon: <IconAppWindow />,
    text: "Github.com/Joram3000",
    url: "https://github.com/joram3000",
  },
]
